name: CI Pipeline
on:
  push:
    branches: [main,Assignment5_MLOPs_Basics]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Assignment_5_MLOps_Basics/requirements.txt
        
    - name: Train model
      run: |
        python Assignment_5_MLOps_Basics/train.py
        
    - name: Run tests
      run: |
        pytest Assignment_5_MLOps_Basics/tests/test_model.py -v
        
    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: Assignment_5_MLOps_Basics/models/